[workspace]
resolver = "2"
members = [
    "crates/argos_core",
    "crates/argos_io",
    "crates/argos_app",
]

[workspace.package]
version = "0.9.0"
edition = "2021"
authors = ["Breno"]
license = "MIT"
