[workspace]
resolver = "2"
members = [
    "crates/scav_core",
    "crates/scav_io",
    "crates/scav_app",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Breno"]
license = "MIT"
