[package]
name = "argos_core"
description = "Core domain definitions and traits for Argos tool"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
thiserror = "2.0.17"
memchr = "2.7.6"
imagesize = "0.14.0"
